### PR TITLE
update to ubuntu 20.04 and install git

### PR DESCRIPTION
**Pull request by Mettbrot**
I believe every docker image should have git to be useful an versatile in a CI environment.

### CODE REVIEW

**Comment by hrektts** [comment]
Thank you for the update!

**Comment by Mettbrot** [comment]
Thanks!

**Comment by Mettbrot** [comment]
Any idea why the image on dockerhub is not updating? 
https://hub.docker.com/r/hrektts/doxygen/builds

**Comment by hrektts** [comment]
The automated build was broken. Now we can pull it from Docker Hub :)
https://hub.docker.com/layers/hrektts/doxygen/latest/images/sha256-1e0795a514d8a9e07db5a1db3dfefe500f502dde3a4608c94630749f3726b0ff?context=explore

**Pull request merged**
